import Foundation

/// Ranks who to text and pairs each person with an opener.
/// Pure and synchronous so the widget can run it in microseconds without touching the network.
public enum SuggestionEngine {
    /// Openers older than this are treated as stale and regenerated by the app.
    public static let openerMaxAge: TimeInterval = 20 * 60 * 60

    public static func suggestions(
        people: [Person],
        openers: [UUID: Opener],
        context: LifeContext,
        now: Date = .now,
        calendar: Calendar = .current,
        includeUpToDate: Bool = false
    ) -> [Suggestion] {
        let today = calendar.startOfDay(for: now)
        return people
            .filter { p in
                guard let snooze = p.snoozedUntil else { return true }
                return snooze <= now
            }
            .map { p -> Suggestion in
                let days = p.lastContacted.map {
                    calendar.dateComponents([.day], from: calendar.startOfDay(for: $0), to: today).day ?? 0
                }
                let score = days.map { Double(max(0, $0)) / Double(max(1, p.cadenceDays)) } ?? 1.5
                let opener = openers[p.id].flatMap { isFresh($0, now: now) ? $0 : nil }
                    ?? fallbackOpener(for: p, context: context, now: now, calendar: calendar)
                return Suggestion(
                    person: p,
                    daysSince: days.map { max(0, $0) },
                    urgency: urgency(forScore: score),
                    score: score,
                    opener: opener
                )
            }
            .filter { includeUpToDate || $0.urgency >= .dueSoon }
            .sorted { a, b in
                if a.urgency != b.urgency { return a.urgency > b.urgency }
                if a.person.isFavorite != b.person.isFavorite { return a.person.isFavorite }
                if a.score != b.score { return a.score > b.score }
                return a.person.name.localizedCaseInsensitiveCompare(b.person.name) == .orderedAscending
            }
    }

    public static func urgency(forScore score: Double) -> Urgency {
        switch score {
        case 1.5...: return .overdue
        case 1.0..<1.5: return .due
        case 0.75..<1.0: return .dueSoon
        default: return .upToDate
        }
    }

    public static func isFresh(_ opener: Opener, now: Date) -> Bool {
        now.timeIntervalSince(opener.createdAt) < openerMaxAge
    }

    // MARK: - Offline openers

    /// A reasonable opener with no network. Rotates daily so it doesn't feel canned,
    /// and weaves in the person's notes or your own projects when there are any.
    public static func fallbackOpener(
        for person: Person,
        context: LifeContext,
        now: Date = .now,
        calendar: Calendar = .current
    ) -> Opener {
        let name = person.firstName
        var options: [String] = [
            "Hey \(name)! Was just thinking about you — how's your week going?",
            "Hi \(name), it's been a minute! What's new with you?",
            "Hey \(name)! How are you doing? Would love to catch up.",
        ]
        if let topic = firstLine(of: person.notes) {
            options.append("Hey \(name)! How's everything going with \(topic)?")
            options.append("Hi \(name) — been wondering about \(topic). Any updates?")
        }
        if let project = context.projects.first(where: { !$0.trimmingCharacters(in: .whitespaces).isEmpty }) {
            options.append("Hey \(name)! I've been busy working on \(project) — how have you been?")
        }
        let day = calendar.ordinality(of: .day, in: .era, for: now) ?? 0
        let index = (stableSeed(person.id) &+ day) % options.count
        return Opener(personID: person.id, text: options[index], isAI: false, createdAt: now)
    }

    static func firstLine(of notes: String) -> String? {
        let line = notes.split(whereSeparator: \.isNewline).first.map(String.init)?
            .trimmingCharacters(in: .whitespacesAndNewlines.union(.init(charactersIn: ".!")))
        guard let line, !line.isEmpty, line.count <= 60 else { return nil }
        return line
    }

    /// Deterministic across launches (unlike `hashValue`), so the widget and app agree.
    static func stableSeed(_ id: UUID) -> Int {
        withUnsafeBytes(of: id.uuid) { bytes in
            bytes.reduce(0) { ($0 &* 31 &+ Int($1)) & 0x7fff_ffff }
        }
    }
}
